/// <reference types="node" />
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Infer workout location from equipment list.
 * Any gym-specific piece of equipment (barbell, cables, machines, benches, etc.)
 * forces GYM-only. Pure bodyweight / dumbbells / bands / kettlebell → HOME + GYM.
 */
function inferLocation(equipment: string[]): string[] {
  const gymOnlyKeywords = ['barbell', 'cable', 'machine', 'bench', 'dip station', 'preacher', 'rack', 'plate', 'functional'];
  const hasGymOnly = equipment.some(e =>
    gymOnlyKeywords.some(k => e.toLowerCase().includes(k))
  );
  return hasGymOnly ? ['GYM'] : ['HOME', 'GYM'];
}

const exercises = [
  // ─── CHEST ───────────────────────────────────────────────────────────────
  { name: 'Barbell Bench Press', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid', 'Triceps'], equipment: ['barbell', 'bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Retract scapula', 'Drive feet into floor', 'Touch bar to lower chest', 'Full lockout at top'], commonMistakes: ['Flared elbows', 'Bouncing off chest', 'Lifting hips off bench'], metValue: 6.0 },
  { name: 'Incline Barbell Bench Press', primaryMuscle: 'Upper Chest', secondaryMuscles: ['Front Deltoid', 'Triceps'], equipment: ['barbell', 'incline bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['30-45 degree incline', 'Retract scapula', 'Lower bar to upper chest'], commonMistakes: ['Too steep incline becomes shoulder press', 'Loose upper back'], metValue: 6.0 },
  { name: 'Dumbbell Bench Press', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid', 'Triceps'], equipment: ['dumbbells', 'bench'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Greater range of motion than barbell', 'Control descent', 'Neutral or pronated grip'], commonMistakes: ['Dumbbells too wide at bottom', 'Uneven range of motion'], metValue: 5.5 },
  { name: 'Incline Dumbbell Press', primaryMuscle: 'Upper Chest', secondaryMuscles: ['Front Deltoid', 'Triceps'], equipment: ['dumbbells', 'incline bench'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['30-45 degree incline', 'Full stretch at bottom'], commonMistakes: ['Too heavy limiting range of motion'], metValue: 5.5 },
  { name: 'Cable Fly', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Slight elbow bend throughout', 'Squeeze at peak contraction', 'Feel stretch at start'], commonMistakes: ['Bending elbows too much (becomes press)', 'Not achieving full stretch'], metValue: 4.0 },
  { name: 'Dumbbell Fly', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid'], equipment: ['dumbbells', 'bench'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Slight bend in elbows maintained', 'Deep stretch at bottom', 'Hug a tree motion'], commonMistakes: ['Going too heavy losing form', 'Excessive elbow bend'], metValue: 4.0 },
  { name: 'Push-Up', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid', 'Triceps', 'Core'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Straight body plank position', 'Hands slightly wider than shoulders', 'Full range of motion'], commonMistakes: ['Sagging hips', 'Flared elbows', 'Incomplete range'], metValue: 4.5 },
  { name: 'Decline Barbell Bench Press', primaryMuscle: 'Lower Chest', secondaryMuscles: ['Triceps', 'Front Deltoid'], equipment: ['barbell', 'decline bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Feet secured', 'Lower to lower chest', 'Full lockout'], commonMistakes: ['Not securing feet', 'Too much decline negates benefit'], metValue: 6.0 },
  { name: 'Machine Chest Press', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid', 'Triceps'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Adjust seat so handles align with chest', 'Full range of motion'], commonMistakes: ['Seat too high or too low', 'Shrugging shoulders'], metValue: 4.5 },
  { name: 'Low-to-High Cable Fly', primaryMuscle: 'Upper Chest', secondaryMuscles: ['Front Deltoid'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Cables set at lowest position', 'Arc upward and inward', 'Cross at top'], commonMistakes: ['Using too much weight', 'Not crossing cables for peak contraction'], metValue: 4.0 },
  { name: 'Chest Dip', primaryMuscle: 'Lower Chest', secondaryMuscles: ['Triceps', 'Front Deltoid'], equipment: ['bodyweight', 'dip station'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Lean forward for chest emphasis', 'Deep dip to feel stretch', 'Slow descent'], commonMistakes: ['Staying too upright (becomes tricep dip)', 'Not going deep enough'], metValue: 5.5 },
  { name: 'Pec Deck Machine', primaryMuscle: 'Chest', secondaryMuscles: ['Front Deltoid'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Elbows at 90 degrees', 'Squeeze at peak contraction', 'Control eccentric'], commonMistakes: ['Going too heavy losing form', 'Letting weight drop on return'], metValue: 4.0 },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  { name: 'Deadlift', primaryMuscle: 'Lower Back', secondaryMuscles: ['Hamstrings', 'Glutes', 'Traps', 'Core'], equipment: ['barbell'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Bar over mid-foot', 'Hip hinge to initiate', 'Lat engagement before lift', 'Lock hips at top'], commonMistakes: ['Rounding lower back', 'Bar drifting from body', 'Jerking off floor'] },
  { name: 'Pull-Up', primaryMuscle: 'Lats', secondaryMuscles: ['Biceps', 'Rear Deltoid', 'Core'], equipment: ['bodyweight', 'pull-up bar'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Depress and retract scapula', 'Drive elbows to hips', 'Full hang at bottom'], commonMistakes: ['Incomplete range of motion', 'Kipping when not intended', 'Not engaging lats'] },
  { name: 'Lat Pulldown', primaryMuscle: 'Lats', secondaryMuscles: ['Biceps', 'Rear Deltoid'], equipment: ['cables', 'machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Lean back slightly', 'Drive elbows to floor', 'Squeeze lats at bottom'], commonMistakes: ['Pulling with biceps', 'Excessive lean back', 'Partial range'] },
  { name: 'Barbell Row', primaryMuscle: 'Middle Back', secondaryMuscles: ['Lats', 'Biceps', 'Rear Deltoid'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Hip hinge ~45 degrees', 'Pull to lower stomach', 'Elbows back not flared'], commonMistakes: ['Jerking with lower back', 'Pulling to chest', 'Not retracting scapula'] },
  { name: 'Dumbbell Row', primaryMuscle: 'Lats', secondaryMuscles: ['Biceps', 'Rear Deltoid', 'Middle Back'], equipment: ['dumbbells', 'bench'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Flat back', 'Pull elbow to ceiling', 'Full stretch at bottom'], commonMistakes: ['Rotating torso', 'Insufficient range of motion'] },
  { name: 'Seated Cable Row', primaryMuscle: 'Middle Back', secondaryMuscles: ['Lats', 'Biceps'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Sit tall', 'Retract scapula first', 'Pull to lower abs'], commonMistakes: ['Rounding back to reach forward', 'Not achieving full scapular retraction'] },
  { name: 'Romanian Deadlift', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Lower Back'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Soft bend in knees', 'Hip hinge keeping bar close', 'Feel hamstring stretch', 'Squeeze glutes at top'], commonMistakes: ['Rounding back', 'Squatting instead of hinging'] },
  { name: 'Face Pull', primaryMuscle: 'Rear Deltoid', secondaryMuscles: ['Rotator Cuff', 'Middle Traps'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Cable at upper-face height', 'Pull to forehead with external rotation', 'Hold contraction'], commonMistakes: ['Pulling to neck instead of face', 'No external rotation'] },
  { name: 'Hyperextension', primaryMuscle: 'Lower Back', secondaryMuscles: ['Glutes', 'Hamstrings'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Hinge at hips not waist', 'Keep neutral spine', 'Squeeze glutes at top'], commonMistakes: ['Hyperextending lumbar', 'Rounding at bottom'] },
  { name: 'T-Bar Row', primaryMuscle: 'Middle Back', secondaryMuscles: ['Lats', 'Biceps'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Chest supported version is safer', 'Pull to lower chest', 'Retract scapula'], commonMistakes: ['Too much weight causing form breakdown'] },
  { name: 'Chin-Up', primaryMuscle: 'Lats', secondaryMuscles: ['Biceps', 'Rear Deltoid'], equipment: ['bodyweight', 'pull-up bar'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Supinated grip emphasizes biceps', 'Full hang to full flexion', 'Slow descent'], commonMistakes: ['Incomplete range of motion', 'No scapular engagement'] },
  { name: 'Rack Pull', primaryMuscle: 'Traps', secondaryMuscles: ['Lower Back', 'Glutes', 'Hamstrings'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Set bar at knee height', 'Same setup as deadlift', 'Overload friendly variation'], commonMistakes: ['Too much weight before technique is solid'] },
  { name: 'Wide-Grip Lat Pulldown', primaryMuscle: 'Lats', secondaryMuscles: ['Rear Deltoid', 'Biceps'], equipment: ['cables', 'machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Grip wider than shoulder width', 'Arc bar to upper chest', 'Keep chest up'], commonMistakes: ['Pulling behind neck', 'Losing lat connection'] },
  { name: 'Straight-Arm Pulldown', primaryMuscle: 'Lats', secondaryMuscles: ['Core', 'Triceps'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Keep arms straight throughout', 'Pull from above head to hips', 'Hinge slightly at hips'], commonMistakes: ['Bending elbows', 'Not engaging lats'] },
  { name: 'Meadows Row', primaryMuscle: 'Lats', secondaryMuscles: ['Middle Back', 'Biceps'], equipment: ['barbell'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Landmine setup', 'Pull with elbow flared', 'Full stretch at bottom'], commonMistakes: ['Not loading plates appropriately'] },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────
  { name: 'Overhead Press', primaryMuscle: 'Front Deltoid', secondaryMuscles: ['Middle Deltoid', 'Triceps', 'Upper Traps'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Bar starts at clavicle', 'Press in straight line', 'Lock out overhead', 'Brace core'], commonMistakes: ['Excessive lower back arch', 'Forward bar path', 'Not reaching full lockout'] },
  { name: 'Dumbbell Shoulder Press', primaryMuscle: 'Front Deltoid', secondaryMuscles: ['Middle Deltoid', 'Triceps'], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Seated or standing', 'Elbows at 90 degrees start', 'Press to lockout'], commonMistakes: ['Too wide elbow path straining shoulder', 'Arching back when seated'] },
  { name: 'Lateral Raise', primaryMuscle: 'Middle Deltoid', secondaryMuscles: ['Front Deltoid'], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Slight forward lean', 'Lead with elbows', 'Pinky slightly higher than thumb', 'Stop at shoulder height'], commonMistakes: ['Swinging for momentum', 'Going above parallel', 'Too heavy'] },
  { name: 'Cable Lateral Raise', primaryMuscle: 'Middle Deltoid', secondaryMuscles: ['Front Deltoid'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Cable at lowest position', 'Raise across body', 'Constant tension throughout'], commonMistakes: ['Too much torso lean', 'Not crossing midline'] },
  { name: 'Front Raise', primaryMuscle: 'Front Deltoid', secondaryMuscles: ['Middle Deltoid'], equipment: ['dumbbells', 'barbell'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Raise to shoulder height', 'Slight elbow bend', 'Control descent'], commonMistakes: ['Swinging torso', 'Going too high'] },
  { name: 'Rear Delt Fly', primaryMuscle: 'Rear Deltoid', secondaryMuscles: ['Middle Traps', 'Rhomboids'], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Hinge forward 45-90 degrees', 'Lead with elbows', 'Squeeze rear delts at top'], commonMistakes: ['Too heavy losing form', 'Using traps instead of rear delts'] },
  { name: 'Arnold Press', primaryMuscle: 'Front Deltoid', secondaryMuscles: ['Middle Deltoid', 'Triceps'], equipment: ['dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Start with palms facing you', 'Rotate out as you press', 'End palms forward at top'], commonMistakes: ['Rushing the rotation', 'Too heavy to maintain rotation'] },
  { name: 'Upright Row', primaryMuscle: 'Middle Deltoid', secondaryMuscles: ['Front Deltoid', 'Traps', 'Biceps'], equipment: ['barbell', 'cables'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Pull to chin level', 'Elbows lead and flare out', 'Grip wider reduces shoulder impingement'], commonMistakes: ['Narrow grip causing impingement', 'Pulling too high'] },
  { name: 'Machine Shoulder Press', primaryMuscle: 'Front Deltoid', secondaryMuscles: ['Middle Deltoid', 'Triceps'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Adjust seat height', 'Full range of motion', 'Control eccentric'], commonMistakes: ['Seat too low causing impingement'] },
  { name: 'Barbell Shrug', primaryMuscle: 'Traps', secondaryMuscles: ['Neck'], equipment: ['barbell'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Straight up not rolling', 'Hold contraction 1 second', 'Full range down'], commonMistakes: ['Rolling shoulders (outdated advice)', 'Too much weight limiting range'] },
  { name: 'Dumbbell Shrug', primaryMuscle: 'Traps', secondaryMuscles: ['Neck'], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Straight up shrug', 'Full squeeze at top', 'Control the descent'], commonMistakes: ['Partial range of motion', 'Leaning forward'] },
  { name: 'Landmine Press', primaryMuscle: 'Front Deltoid', secondaryMuscles: ['Upper Chest', 'Triceps'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Neutral grip feels more natural', 'Press in arc motion', 'Good shoulder mobility option'], commonMistakes: ['Not stabilizing the landmine base'] },

  // ─── BICEPS ───────────────────────────────────────────────────────────────
  { name: 'Barbell Curl', primaryMuscle: 'Biceps', secondaryMuscles: ['Forearms', 'Front Deltoid'], equipment: ['barbell'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Elbows pinned to sides', 'Full supination at top', 'Slow eccentric'], commonMistakes: ['Swinging torso', 'Partial range of motion', 'Elbows drifting forward'] },
  { name: 'Dumbbell Curl', primaryMuscle: 'Biceps', secondaryMuscles: ['Forearms'], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Supinate wrist as you curl', 'Alternate or simultaneous', 'Full stretch at bottom'], commonMistakes: ['No supination', 'Swinging'] },
  { name: 'Hammer Curl', primaryMuscle: 'Brachialis', secondaryMuscles: ['Biceps', 'Forearms'], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Neutral grip throughout', 'Elbows pinned to sides', 'Full range of motion'], commonMistakes: ['Swinging', 'Partial reps'] },
  { name: 'Incline Dumbbell Curl', primaryMuscle: 'Biceps', secondaryMuscles: ['Forearms'], equipment: ['dumbbells', 'incline bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Arms hang behind torso for full stretch', 'Supinate at top', 'Perfect isolation'], commonMistakes: ['Too heavy losing the stretch benefit'] },
  { name: 'Preacher Curl', primaryMuscle: 'Biceps', secondaryMuscles: ['Brachialis'], equipment: ['barbell', 'machines', 'preacher bench'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Upper arm flat on pad', 'Full range of motion', 'Hold squeeze at top'], commonMistakes: ['Locking out at bottom with force', 'Partial range'] },
  { name: 'Cable Curl', primaryMuscle: 'Biceps', secondaryMuscles: ['Forearms'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Constant cable tension', 'Great for peak contraction', 'Squeeze and hold'], commonMistakes: ['Elbows drifting forward', 'No peak contraction hold'] },
  { name: 'Concentration Curl', primaryMuscle: 'Biceps', secondaryMuscles: [], equipment: ['dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Elbow braced on inner thigh', 'Full supination at top', 'Perfect isolation exercise'], commonMistakes: ['Elbow not braced', 'No supination'] },
  { name: 'EZ Bar Curl', primaryMuscle: 'Biceps', secondaryMuscles: ['Forearms'], equipment: ['barbell'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Semi-supinated grip reduces wrist stress', 'Same cues as barbell curl', 'Good for wrist pain sufferers'], commonMistakes: ['Swinging', 'Partial range'] },
  { name: 'Reverse Curl', primaryMuscle: 'Brachialis', secondaryMuscles: ['Forearms', 'Biceps'], equipment: ['barbell', 'cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Pronated grip', 'Curl to shoulder height', 'Great brachialis isolator'], commonMistakes: ['Wrist dropping', 'Too heavy'] },
  { name: 'Spider Curl', primaryMuscle: 'Biceps', secondaryMuscles: [], equipment: ['dumbbells', 'incline bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Prone on incline bench', 'Arms hang straight down', 'Full supinated curl'], commonMistakes: ['Elbow movement forward', 'Not achieving full supination'] },

  // ─── TRICEPS ──────────────────────────────────────────────────────────────
  { name: 'Close-Grip Bench Press', primaryMuscle: 'Triceps', secondaryMuscles: ['Front Deltoid', 'Chest'], equipment: ['barbell', 'bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Grip slightly narrower than shoulder width', 'Elbows tucked at 45 degrees', 'Compound tricep movement'], commonMistakes: ['Too narrow grip straining wrists', 'Flaring elbows'] },
  { name: 'Tricep Dip', primaryMuscle: 'Triceps', secondaryMuscles: ['Chest', 'Front Deltoid'], equipment: ['bodyweight', 'dip station'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Torso upright for tricep emphasis', 'Elbows track backward', 'Full lockout'], commonMistakes: ['Leaning forward shifting to chest', 'Partial range'] },
  { name: 'Overhead Tricep Extension', primaryMuscle: 'Triceps Long Head', secondaryMuscles: ['Triceps'], equipment: ['dumbbells', 'cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Elbows point to ceiling', 'Only forearms move', 'Full stretch in long head'], commonMistakes: ['Flaring elbows out', 'Not achieving full stretch'] },
  { name: 'Skull Crusher', primaryMuscle: 'Triceps', secondaryMuscles: [], equipment: ['barbell', 'dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Lower bar to forehead or above', 'Elbows stay vertical', 'Slow eccentric'], commonMistakes: ['Elbows flaring out', 'Elbows drifting back (becomes pullover)'] },
  { name: 'Tricep Pushdown', primaryMuscle: 'Triceps', secondaryMuscles: [], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Elbows pinned to sides', 'Full lockout at bottom', 'Control the return'], commonMistakes: ['Elbows drifting forward', 'Using bodyweight to push down'] },
  { name: 'Rope Pushdown', primaryMuscle: 'Triceps', secondaryMuscles: [], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Spread the rope at bottom', 'Flare hands at peak contraction', 'Elbows stay pinned'], commonMistakes: ['No flare at bottom losing contraction', 'Swinging torso'] },
  { name: 'Diamond Push-Up', primaryMuscle: 'Triceps', secondaryMuscles: ['Inner Chest', 'Front Deltoid'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Hands form diamond shape under chest', 'Elbows track backward not out'], commonMistakes: ['Hands too far forward', 'Flared elbows'] },
  { name: 'Reverse Grip Pushdown', primaryMuscle: 'Triceps Long Head', secondaryMuscles: ['Triceps'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Supinated grip', 'Emphasizes long head', 'Elbows pinned'], commonMistakes: ['Wrist breaking', 'Elbows drifting'] },
  { name: 'Tate Press', primaryMuscle: 'Triceps', secondaryMuscles: [], equipment: ['dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Start with dumbbells extended over chest', 'Tilt towards forehead', 'Lower to chest level'], commonMistakes: ['Too heavy losing wrist control'] },
  { name: 'JM Press', primaryMuscle: 'Triceps', secondaryMuscles: ['Front Deltoid', 'Chest'], equipment: ['barbell'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Hybrid of close-grip bench and skull crusher', 'Bar travels toward throat', 'Elbows high'], commonMistakes: ['Form breaks under heavy load'] },

  // ─── QUADS / LEGS ─────────────────────────────────────────────────────────
  { name: 'Barbell Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings', 'Core', 'Calves'], equipment: ['barbell'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Bar on traps or low back', 'Brace core', 'Knees track over toes', 'Drive through whole foot'], commonMistakes: ['Knees caving', 'Forward lean', 'Heel rise', 'Not hitting depth'] },
  { name: 'Front Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Core', 'Upper Back', 'Glutes'], equipment: ['barbell'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Bar rests on front delts', 'High elbows', 'Upright torso', 'Knees track over toes'], commonMistakes: ['Elbows dropping losing rack', 'Rounding upper back'] },
  { name: 'Leg Press', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Low foot placement for quads', 'High foot placement for glutes', 'Never lock knees under load'], commonMistakes: ['Locking knees', 'Back lifting off pad', 'Partial range'] },
  { name: 'Hack Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings'], equipment: ['machines'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Low foot placement emphasizes quads', 'Full depth if mobility allows', 'Brace core'], commonMistakes: ['Too much forward knee travel', 'Partial range'] },
  { name: 'Leg Extension', primaryMuscle: 'Quadriceps', secondaryMuscles: [], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Seat adjusted so knee aligns with pivot', 'Full extension with hold', 'Slow eccentric'], commonMistakes: ['Too heavy causing knee stress', 'Not adjusting seat', 'Partial range'] },
  { name: 'Bulgarian Split Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'], equipment: ['dumbbells', 'barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Rear foot elevated', 'Torso upright', 'Front knee tracks over toes', 'Drop straight down'], commonMistakes: ['Forward lean shifting to glutes', 'Knee collapsing inward'] },
  { name: 'Goblet Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Core'], equipment: ['dumbbells', 'kettlebell'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Hold dumbbell at chest', 'Elbows track inside knees', 'Chest stays tall'], commonMistakes: ['Forward lean', 'Knees caving'] },
  { name: 'Walking Lunge', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'], equipment: ['dumbbells', 'barbell', 'bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Long stride', 'Knee barely touches floor', 'Drive through front heel to stand', 'Upright torso'], commonMistakes: ['Short stride causing knee to go over toes', 'Torso leaning forward'] },
  { name: 'Step-Up', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings'], equipment: ['dumbbells', 'bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Step height at or below knee', 'Drive through heel', 'Keep torso upright'], commonMistakes: ['Pushing off back foot (cheating)', 'Leaning forward'] },
  { name: 'Sissy Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: [], equipment: ['bodyweight'], difficulty: 'ADVANCED' as const, mechanics: 'ISOLATION' as const, force: 'SQUAT' as const, cues: ['Hold support for balance', 'Lean back as knees travel forward', 'Heels raised', 'Full range of motion'], commonMistakes: ['Insufficient range of motion', 'No support when starting out'] },
  { name: 'Box Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Sit to box — control the descent', 'Brief pause on box', 'Drive up hard'], commonMistakes: ['Bouncing off box', 'Relaxing posterior chain on box'] },
  { name: 'Sumo Deadlift', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Hamstrings', 'Inner Thigh'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Wide stance toes out', 'Grip inside legs', 'Push floor away', 'Drive hips forward at top'], commonMistakes: ['Hips shooting up at start', 'Knees caving inward'] },
  { name: 'Landmine Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: ['Glutes', 'Core'], equipment: ['barbell'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Hold bar at chest', 'Deep squat', 'Squat therapy movement'], commonMistakes: ['Not going deep enough'] },
  { name: 'Cyclist Squat', primaryMuscle: 'Quadriceps', secondaryMuscles: [], equipment: ['barbell', 'dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'SQUAT' as const, cues: ['Heels elevated on plates', 'Torso upright', 'Knees travel far forward', 'VMO emphasis'], commonMistakes: ['Not elevating heels enough', 'Partial range of motion'] },
  { name: 'Quad Extension Machine', primaryMuscle: 'Quadriceps', secondaryMuscles: [], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Full extension with isometric hold', 'Slow controlled eccentric', 'Adjust seat so knee aligns with pivot'], commonMistakes: ['Too heavy', 'Not full extension'] },

  // ─── HAMSTRINGS ───────────────────────────────────────────────────────────
  { name: 'Leg Curl', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Calves'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Lying or seated', 'Full range of motion', 'Hold peak contraction'], commonMistakes: ['Partial range of motion', 'Hips lifting off pad in lying version'] },
  { name: 'Nordic Hamstring Curl', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Core'], equipment: ['bodyweight'], difficulty: 'ADVANCED' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Knees on pad', 'Lower as slowly as possible', 'Catch with hands if needed', 'Eccentric overload king'], commonMistakes: ['Going too fast', 'Not progressing properly'] },
  { name: 'Good Morning', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Lower Back', 'Glutes'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Hip hinge with bar on traps', 'Soft knee bend', 'Feel hamstring stretch at bottom'], commonMistakes: ['Rounding lower back', 'Too much weight'] },
  { name: 'Stiff-Leg Deadlift', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Lower Back'], equipment: ['barbell', 'dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Legs completely straight', 'Bar stays close to shins', 'Feel maximum hamstring stretch'], commonMistakes: ['Rounding back', 'Too much weight'] },
  { name: 'Single-Leg Deadlift', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Core'], equipment: ['dumbbells', 'barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Balance on one leg', 'Hip hinge keeping hips square', 'Slight knee bend on standing leg'], commonMistakes: ['Hips rotating open', 'Losing balance from going too heavy'] },
  { name: 'Seated Leg Curl', primaryMuscle: 'Hamstrings', secondaryMuscles: [], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Better hip flexion angle for full stretch', 'Full range of motion', 'Squeeze at peak contraction'], commonMistakes: ['Partial range of motion'] },
  { name: 'Glute Ham Raise', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Calves', 'Lower Back'], equipment: ['machines'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Use GHD machine', 'Full range: lower parallel to floor to upright'], commonMistakes: ['Partial range of motion', 'Hips not in proper position'] },
  { name: 'Cable Pull-Through', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Lower Back'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Cable between legs from low position', 'Hip hinge pattern', 'Squeeze glutes at top'], commonMistakes: ['Squatting instead of hinging', 'Arms driving the movement'] },
  { name: 'Swiss Ball Leg Curl', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Core'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Heels on ball', 'Bridge hips up', 'Curl ball to glutes maintaining bridge'], commonMistakes: ['Hips dropping', 'Not maintaining bridge height'] },
  { name: 'Banded Good Morning', primaryMuscle: 'Hamstrings', secondaryMuscles: ['Glutes', 'Lower Back'], equipment: ['bands'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Band under feet and on shoulders', 'Hip hinge pattern', 'Good warm-up movement'], commonMistakes: ['Rounding lower back'] },

  // ─── GLUTES ───────────────────────────────────────────────────────────────
  { name: 'Barbell Hip Thrust', primaryMuscle: 'Glutes', secondaryMuscles: ['Hamstrings', 'Core'], equipment: ['barbell', 'bench'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Shoulder blades on bench', 'Bar in hip crease with pad', 'Drive hips up to full extension', 'Posterior pelvic tilt at top'], commonMistakes: ['Not reaching full hip extension', 'Lower back taking over', 'Neck craning up'] },
  { name: 'Glute Bridge', primaryMuscle: 'Glutes', secondaryMuscles: ['Hamstrings', 'Core'], equipment: ['bodyweight', 'barbell'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Floor variation of hip thrust', 'Drive hips to full extension', 'Hold 1-2 seconds at top', 'Posterior pelvic tilt'], commonMistakes: ['Lower back arching at top', 'Feet too far from hips'] },
  { name: 'Cable Kickback', primaryMuscle: 'Glutes', secondaryMuscles: ['Hamstrings'], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Ankle strap attachment', 'Hip extension not hyperextension', 'Squeeze at top'], commonMistakes: ['Swinging leg using momentum', 'Hip flexor doing the work'] },
  { name: 'Donkey Kick', primaryMuscle: 'Glutes', secondaryMuscles: [], equipment: ['bodyweight', 'cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['On hands and knees', 'Push heel to ceiling', 'Squeeze glute at top', 'Maintain neutral spine'], commonMistakes: ['Arching lower back', 'Rotating hips'] },
  { name: 'Sumo Squat', primaryMuscle: 'Glutes', secondaryMuscles: ['Inner Thigh', 'Quadriceps'], equipment: ['dumbbells', 'kettlebell'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Wide stance toes pointed out 45 degrees', 'Hold weight between legs', 'Knees track over toes'], commonMistakes: ['Knees caving inward', 'Not going deep enough'] },
  { name: 'Side-Lying Hip Abduction', primaryMuscle: 'Glutes (Medius)', secondaryMuscles: ['Glutes (Minimus)'], equipment: ['bodyweight', 'bands'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Lie on side', 'Raise leg to 45 degrees', 'Lead with heel'], commonMistakes: ['Rotating hip forward', 'Going too fast'] },
  { name: 'Monster Walk', primaryMuscle: 'Glutes (Medius)', secondaryMuscles: ['Quadriceps'], equipment: ['bands'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Band around ankles or knees', 'Slight squat position', 'Maintain tension throughout', 'Control each step'], commonMistakes: ['Standing straight up', 'Letting band go slack'] },
  { name: 'Bulgarian Split Squat with Forward Lean', primaryMuscle: 'Glutes', secondaryMuscles: ['Hamstrings', 'Quadriceps'], equipment: ['dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'SQUAT' as const, cues: ['Rear foot elevated', 'Lean torso forward 30-45 degrees', 'Shifts emphasis to glutes/hamstrings from quads'], commonMistakes: ['Insufficient lean', 'Rear knee hitting floor hard'] },
  { name: 'Hip Abduction Machine', primaryMuscle: 'Glutes (Medius)', secondaryMuscles: [], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Seated or lying version', 'Full range of motion', 'Slow and controlled', 'Squeeze glutes throughout'], commonMistakes: ['Too much weight and speed', 'Partial range'] },
  { name: 'Clamshell', primaryMuscle: 'Glutes (Medius)', secondaryMuscles: ['Hip External Rotators'], equipment: ['bodyweight', 'bands'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Side lying with hips at 45 degrees', 'Keep feet together', 'Rotate top knee up like clamshell opening'], commonMistakes: ['Rolling hips back', 'Insufficient range of motion'] },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  { name: 'Plank', primaryMuscle: 'Core', secondaryMuscles: ['Shoulders', 'Glutes'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Straight body line', 'Brace abs like about to be punched', 'Squeeze glutes', 'Look at floor'], commonMistakes: ['Hips sagging', 'Hips too high', 'Holding breath'] },
  { name: 'Cable Crunch', primaryMuscle: 'Abs', secondaryMuscles: [], equipment: ['cables'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Kneel facing cable', 'Crunch elbows to knees', 'Round back — this is the correct form for crunches'], commonMistakes: ['Hip flexors dominating', 'Pulling with arms not abs'] },
  { name: 'Ab Wheel Rollout', primaryMuscle: 'Core', secondaryMuscles: ['Lats', 'Shoulders'], equipment: ['bodyweight'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Brace core hard before rolling out', 'Keep hips at same height', 'Pull in using abs not hip flexors'], commonMistakes: ['Hips shooting up', 'Lower back arching'] },
  { name: 'Hanging Leg Raise', primaryMuscle: 'Lower Abs', secondaryMuscles: ['Hip Flexors', 'Core'], equipment: ['bodyweight', 'pull-up bar'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Dead hang', 'Posterior pelvic tilt then raise', 'Control descent', 'Avoid swinging'], commonMistakes: ['Swinging for momentum', 'Using hip flexors only without pelvic tilt'] },
  { name: 'Russian Twist', primaryMuscle: 'Obliques', secondaryMuscles: ['Core'], equipment: ['bodyweight', 'dumbbells'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Feet elevated for harder variation', 'Rotate from trunk not arms', 'Keep chest up'], commonMistakes: ['Feet on floor making it too easy', 'Moving arms not torso'] },
  { name: 'Side Plank', primaryMuscle: 'Obliques', secondaryMuscles: ['Core', 'Shoulders'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Straight body line from head to feet', 'Stack feet or stagger', 'Avoid hips sagging'], commonMistakes: ['Hips drooping', 'Shortened duration without awareness'] },
  { name: 'Dead Bug', primaryMuscle: 'Core', secondaryMuscles: ['Hip Flexors'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Lower back pressed into floor throughout', 'Opposite arm and leg extend simultaneously', 'Breathe out on extension'], commonMistakes: ['Lower back lifting', 'Moving too fast'] },
  { name: 'Pallof Press', primaryMuscle: 'Core', secondaryMuscles: ['Obliques', 'Shoulders'], equipment: ['cables', 'bands'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Cable perpendicular to body', 'Press out and resist rotation', 'Anti-rotation exercise'], commonMistakes: ['Twisting torso', 'Standing too close to cable'] },
  { name: 'Bicycle Crunch', primaryMuscle: 'Obliques', secondaryMuscles: ['Abs', 'Hip Flexors'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Full rotation of torso', 'Elbow to opposite knee', 'Slow controlled reps beat fast sloppy ones'], commonMistakes: ['Neck pulling', 'Partial rotation', 'Moving too fast'] },
  { name: 'Hollow Body Hold', primaryMuscle: 'Core', secondaryMuscles: ['Hip Flexors', 'Shoulders'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Lower back pressed into floor', 'Arms extended overhead', 'Lower extremities 6 inches off floor', 'Posterior pelvic tilt maintained'], commonMistakes: ['Lower back arching', 'Not maintaining spinal position'] },
  { name: 'Mountain Climber', primaryMuscle: 'Core', secondaryMuscles: ['Shoulders', 'Hip Flexors', 'Cardio'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Maintain plank position', 'Drive knees to chest alternately', 'Keep hips level'], commonMistakes: ['Hips too high', 'Hips bouncing'] },
  { name: 'Weighted Crunch', primaryMuscle: 'Abs', secondaryMuscles: [], equipment: ['dumbbells', 'plates'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Hold plate at chest or overhead', 'Round back — this is the goal', 'Posterior pelvic tilt on the way up'], commonMistakes: ['Neck strain', 'Hip flexors dominating'] },
  { name: 'Toes to Bar', primaryMuscle: 'Abs', secondaryMuscles: ['Hip Flexors', 'Lats', 'Core'], equipment: ['bodyweight', 'pull-up bar'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Full dead hang', 'Kip or strict', 'Touch bar with toes not feet'], commonMistakes: ['Swinging excessively', 'Not touching bar'] },
  { name: 'Dragon Flag', primaryMuscle: 'Core', secondaryMuscles: ['Hip Flexors', 'Lats'], equipment: ['bodyweight', 'bench'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Grip bench behind head', 'Straight body line maintained throughout', 'Lower slowly under control'], commonMistakes: ['Bending at hips', 'Uncontrolled descent'] },
  { name: 'Landmine Twist', primaryMuscle: 'Obliques', secondaryMuscles: ['Core', 'Shoulders'], equipment: ['barbell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Hold barbell end at chest height', 'Rotate torso to sweep arc', 'Keep arms relatively straight'], commonMistakes: ['Moving arms not torso', 'Too much weight'] },

  // ─── CALVES ───────────────────────────────────────────────────────────────
  { name: 'Standing Calf Raise', primaryMuscle: 'Gastrocnemius', secondaryMuscles: ['Soleus'], equipment: ['machines', 'bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Full range: full stretch to full contraction', 'Pause at top and bottom', 'Slow tempo'], commonMistakes: ['Partial range of motion', 'Bouncing at bottom'] },
  { name: 'Seated Calf Raise', primaryMuscle: 'Soleus', secondaryMuscles: ['Gastrocnemius'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Knees at 90 degrees', 'Full range of motion', 'Soleus is worked more when knee is bent'], commonMistakes: ['Partial range', 'Going too heavy'] },
  { name: 'Single-Leg Calf Raise', primaryMuscle: 'Gastrocnemius', secondaryMuscles: ['Soleus'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Hold something for balance only', 'Full range of motion', 'Good overload without equipment'], commonMistakes: ['Using support to cheat weight', 'Partial range'] },
  { name: 'Donkey Calf Raise', primaryMuscle: 'Gastrocnemius', secondaryMuscles: ['Soleus'], equipment: ['machines', 'bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Hip hinge position provides better stretch', 'Preferred by many bodybuilders', 'Full range'], commonMistakes: ['Not achieving full hip hinge position'] },
  { name: 'Tibialis Raise', primaryMuscle: 'Tibialis Anterior', secondaryMuscles: [], equipment: ['bodyweight', 'bands'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Heel on elevated surface', 'Dorsiflex (pull toes up)', 'Prevents shin splints', 'Balances calf work'], commonMistakes: ['Not training this antagonist muscle'] },
  { name: 'Jump Rope', primaryMuscle: 'Calves', secondaryMuscles: ['Core', 'Cardio', 'Coordination'], equipment: ['bodyweight'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Land on balls of feet', 'Small jumps efficient', 'Wrists do the rotation not arms'], commonMistakes: ['Landing flat-footed', 'Arms doing all the work'] },
  { name: 'Box Jump Calf Emphasis', primaryMuscle: 'Calves', secondaryMuscles: ['Quadriceps', 'Glutes'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Land softly on box', 'Use arms for momentum', 'Calf explosion at takeoff'], commonMistakes: ['Stiff landing', 'Too-high box increasing fall risk'] },
  { name: 'Leg Press Calf Raise', primaryMuscle: 'Gastrocnemius', secondaryMuscles: ['Soleus'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Toes on edge of platform', 'Full range of motion', 'Can be loaded heavily'], commonMistakes: ['Platform slipping', 'Partial range'] },

  // ─── CARDIO / CONDITIONING ────────────────────────────────────────────────
  { name: 'Treadmill Run', primaryMuscle: 'Cardio', secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Calves', 'Glutes'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Maintain natural running form', 'Land midfoot not heel', 'Slight forward lean from ankles'], commonMistakes: ['Holding handrails', 'Overstriding'] },
  { name: 'Rowing Machine', primaryMuscle: 'Cardio', secondaryMuscles: ['Back', 'Biceps', 'Quadriceps', 'Core'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Sequence: legs-body-arms on pull / arms-body-legs on recovery', 'Drive with legs not arms', 'Maintain upright posture'], commonMistakes: ['Rounding back', 'Arms pulling before legs finish'] },
  { name: 'Assault Bike', primaryMuscle: 'Cardio', secondaryMuscles: ['Shoulders', 'Chest', 'Quadriceps'], equipment: ['machines'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Full body effort', 'Seated for endurance / standing for intensity', 'Brutal but effective'], commonMistakes: ['Not maintaining cadence', 'Hunching over'] },
  { name: 'Battle Rope Slam', primaryMuscle: 'Cardio', secondaryMuscles: ['Shoulders', 'Core', 'Lats'], equipment: ['functional'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Generate power from hips', 'Create large waves', 'Alternate or simultaneous arms'], commonMistakes: ['Arms only — no hip drive', 'Small waves indicating low intensity'] },
  { name: 'Burpee', primaryMuscle: 'Cardio', secondaryMuscles: ['Chest', 'Quadriceps', 'Shoulders', 'Core'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Control descent', 'Chest to floor', 'Jump with arms overhead', 'Continuous movement'], commonMistakes: ['Slow transitions', 'Not fully standing at top'] },
  { name: 'Stair Climber', primaryMuscle: 'Cardio', secondaryMuscles: ['Glutes', 'Quadriceps', 'Calves'], equipment: ['machines'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Upright posture', 'Full step pressing down', 'Do not hold rails for extra support'], commonMistakes: ['Holding rails reducing effort', 'Half-steps'] },
  { name: 'Kettlebell Swing', primaryMuscle: 'Glutes', secondaryMuscles: ['Hamstrings', 'Core', 'Cardio'], equipment: ['kettlebell'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'HINGE' as const, cues: ['Hip hinge power not squat', 'Bell swings from hip drive', 'Brace core at top', 'Arms guide not lift the bell'], commonMistakes: ['Squatting instead of hinging', 'Lower back rounding'] },
  { name: 'Sled Push', primaryMuscle: 'Cardio', secondaryMuscles: ['Quadriceps', 'Glutes', 'Core', 'Shoulders'], equipment: ['functional'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Low body angle for heavy loads', 'Drive from hips', 'Quick short steps'], commonMistakes: ['Standing too upright', 'Not loading appropriately'] },
  { name: 'Sprint Interval', primaryMuscle: 'Cardio', secondaryMuscles: ['Quadriceps', 'Hamstrings', 'Glutes', 'Calves'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Maximal effort sprints', 'Full recovery between intervals', 'Drive arms powerfully'], commonMistakes: ['Not sprinting at true maximum effort', 'Insufficient rest'] },
  { name: 'Box Jump', primaryMuscle: 'Cardio', secondaryMuscles: ['Quadriceps', 'Glutes', 'Calves'], equipment: ['bodyweight'], difficulty: 'INTERMEDIATE' as const, mechanics: 'COMPOUND' as const, force: 'PUSH' as const, cues: ['Jump explosively', 'Land softly on full foot', 'Step down do not jump down'], commonMistakes: ['Landing hard jarring joints', 'Jumping down instead of stepping'] },

  // ─── FOREARMS / GRIP ──────────────────────────────────────────────────────
  { name: 'Wrist Curl', primaryMuscle: 'Forearms (Flexors)', secondaryMuscles: [], equipment: ['dumbbells', 'barbell'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Forearms supported on bench', 'Full range wrist flexion', 'Slow controlled movement'], commonMistakes: ['Too heavy limiting range', 'Moving forearms off bench'] },
  { name: 'Reverse Wrist Curl', primaryMuscle: 'Forearms (Extensors)', secondaryMuscles: [], equipment: ['dumbbells', 'barbell'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'PUSH' as const, cues: ['Pronated grip', 'Extend wrist upward', 'Addresses extensor imbalance'], commonMistakes: ['Too heavy', 'Moving forearms off support'] },
  { name: 'Farmer Carry', primaryMuscle: 'Forearms', secondaryMuscles: ['Traps', 'Core', 'Shoulders', 'Quadriceps'], equipment: ['dumbbells', 'kettlebell'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'CARRY' as const, cues: ['Walk tall', 'Grip tight', 'Brace core', 'Shoulders down and back'], commonMistakes: ['Leaning to one side', 'Short steps'] },
  { name: 'Plate Pinch', primaryMuscle: 'Forearms (Grip)', secondaryMuscles: [], equipment: ['plates'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Pinch two smooth-side-out plates', 'Hold for time', 'Great finger strength builder'], commonMistakes: ['Using rubber plates which are easier'] },
  { name: 'Dead Hang', primaryMuscle: 'Forearms', secondaryMuscles: ['Lats', 'Shoulders'], equipment: ['bodyweight', 'pull-up bar'], difficulty: 'BEGINNER' as const, mechanics: 'COMPOUND' as const, force: 'STATIC' as const, cues: ['Full hang from bar', 'Depress scapula', 'Active vs passive hang for rehab'], commonMistakes: ['Passive hang only without scapular engagement'] },
  { name: 'Towel Pull-Up', primaryMuscle: 'Forearms', secondaryMuscles: ['Biceps', 'Lats'], equipment: ['bodyweight'], difficulty: 'ADVANCED' as const, mechanics: 'COMPOUND' as const, force: 'PULL' as const, cues: ['Loop towels over bar', 'Grip challenge massively increases forearm work'], commonMistakes: ['Slipping — ensure secure towel wrap'] },
  { name: 'Hand Gripper', primaryMuscle: 'Forearms (Grip)', secondaryMuscles: [], equipment: ['functional'], difficulty: 'BEGINNER' as const, mechanics: 'ISOLATION' as const, force: 'STATIC' as const, cues: ['Progress gripper resistance over time', 'Full closure for max benefit', 'Can do timed holds'], commonMistakes: ['Not progressing resistance', 'Partial closure'] },
  { name: 'Zottman Curl', primaryMuscle: 'Forearms', secondaryMuscles: ['Biceps', 'Brachialis'], equipment: ['dumbbells'], difficulty: 'INTERMEDIATE' as const, mechanics: 'ISOLATION' as const, force: 'PULL' as const, cues: ['Curl supinated', 'Rotate to pronated at top', 'Lower with pronated grip', 'Hits all three elbow flexors'], commonMistakes: ['Rushing the rotation', 'Too heavy'] },
];

export async function seedExerciseLibrary() {
  console.log(`📚 Seeding Exercise Library (${exercises.length} exercises)...`);

  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const ex of exercises) {
    const location = inferLocation(ex.equipment);
    try {
      const result = await (prisma as any).exerciseLibrary.upsert({
        where: { name: ex.name },
        update: {
          status: 'APPROVED',
          location,
          fitnessGoals: [],
          isActive: true,
        },
        create: {
          name: ex.name,
          primaryMuscle: ex.primaryMuscle,
          secondaryMuscles: ex.secondaryMuscles,
          equipment: ex.equipment,
          difficulty: ex.difficulty,
          mechanics: ex.mechanics,
          force: ex.force,
          cues: ex.cues,
          commonMistakes: (ex as any).commonMistakes ?? [],
          metValue: (ex as any).metValue ?? 3.0,
          isActive: true,
          status: 'APPROVED',
          location,
          fitnessGoals: [],
        },
      });
      if (result._count !== undefined) updated++; else created++;
    } catch {
      skipped++;
    }
  }

  console.log(`   ✓ Exercise Library: ${created} created, ${updated} updated, ${skipped} skipped`);
  return { created, updated, skipped };
}

// Run standalone
if (require.main === module) {
  seedExerciseLibrary()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
