/// Compile-time English strings — zero heap cost (const).
/// These are the fallback for every translation key in the app.
/// Only fixed UI strings live here. Backend content is never translated.
const Map<String, String> kEn = {
  // ── Common buttons ────────────────────────────────────────────────────────
  'button.save':          'Save',
  'button.cancel':        'Cancel',
  'button.confirm':       'Confirm',
  'button.delete':        'Delete',
  'button.edit':          'Edit',
  'button.back':          'Back',
  'button.next':          'Next',
  'button.done':          'Done',
  'button.retry':         'Retry',
  'button.close':         'Close',
  'button.submit':        'Submit',
  'button.continue':      'Continue',
  'button.skip':          'Skip',
  'button.add':           'Add',
  'button.remove':        'Remove',
  'button.update':        'Update',
  'button.apply':         'Apply',
  'button.generate':      'Generate',
  'button.refresh':       'Refresh',

  // ── Auth ──────────────────────────────────────────────────────────────────
  'auth.login':                   'Login',
  'auth.logout':                  'Logout',
  'auth.email':                   'Email',
  'auth.password':                'Password',
  'auth.confirm_password':        'Confirm Password',
  'auth.forgot_password':         'Forgot Password?',
  'auth.reset_password':          'Reset Password',
  'auth.change_password':         'Change Password',
  'auth.new_password':            'New Password',
  'auth.old_password':            'Current Password',
  'auth.sign_in_google':          'Continue with Google',
  'auth.sign_in_apple':           'Continue with Apple',
  'auth.no_account':              'Don\'t have an account?',
  'auth.has_account':             'Already have an account?',
  'auth.register':                'Register',
  'auth.welcome_back':            'Welcome Back',
  'auth.enter_email':             'Enter your email',
  'auth.enter_password':          'Enter your password',
  'auth.password_changed':        'Password changed successfully',

  // ── Navigation ────────────────────────────────────────────────────────────
  'nav.home':             'Home',
  'nav.workout':          'Workout',
  'nav.diet':             'Diet',
  'nav.gym':              'Gym',
  'nav.dashboard':        'Dashboard',
  'nav.challenge':        'Challenge',
  'nav.progress':         'Progress',
  'nav.profile':          'Profile',
  'nav.settings':         'Settings',

  // ── Dashboard ─────────────────────────────────────────────────────────────
  'dashboard.title':              'Dashboard',
  'dashboard.good_morning':       'Good Morning',
  'dashboard.good_afternoon':     'Good Afternoon',
  'dashboard.good_evening':       'Good Evening',
  'dashboard.weekly_summary':     'Weekly Summary',
  'dashboard.todays_goal':        'Today\'s Goal',
  'dashboard.streak':             'Streak',
  'dashboard.calories':           'Calories',
  'dashboard.steps':              'Steps',
  'dashboard.water':              'Water',
  'dashboard.sleep':              'Sleep',
  'dashboard.recovery':           'Recovery',
  'dashboard.readiness':          'Readiness',
  'dashboard.no_data':            'No data yet',

  // ── Workout ───────────────────────────────────────────────────────────────
  'workout.title':                'Workout',
  'workout.start':                'Start Workout',
  'workout.pause':                'Pause',
  'workout.resume':               'Resume',
  'workout.finish':               'Finish Workout',
  'workout.sets':                 'Sets',
  'workout.reps':                 'Reps',
  'workout.weight':               'Weight',
  'workout.rest':                 'Rest',
  'workout.duration':             'Duration',
  'workout.active_session':       'Active Session',
  'workout.no_plan':              'No workout plan assigned',
  'workout.complete':             'Complete',

  // ── Diet ──────────────────────────────────────────────────────────────────
  'diet.title':                   'Diet',
  'diet.generate_plan':           'Generate Diet Plan',
  'diet.calories':                'Calories',
  'diet.protein':                 'Protein',
  'diet.carbs':                   'Carbs',
  'diet.fat':                     'Fat',
  'diet.breakfast':               'Breakfast',
  'diet.lunch':                   'Lunch',
  'diet.dinner':                  'Dinner',
  'diet.snack':                   'Snack',
  'diet.water_intake':            'Water Intake',
  'diet.no_plan':                 'No diet plan assigned',
  'diet.daily_target':            'Daily Target',

  // ── Gym ───────────────────────────────────────────────────────────────────
  'gym.title':                    'Gym',
  'gym.join':                     'Join Gym',
  'gym.leave':                    'Leave Gym',
  'gym.members':                  'Members',
  'gym.trainer':                  'Trainer',
  'gym.schedule':                 'Schedule',
  'gym.membership':               'Membership',
  'gym.active':                   'Active',
  'gym.expired':                  'Expired',
  'gym.pending':                  'Pending Approval',
  'gym.no_gym':                   'Not a member of any gym',
  'gym.scan_qr':                  'Scan QR Code',
  'gym.register':                 'Register with Gym',

  // ── Settings ──────────────────────────────────────────────────────────────
  'settings.title':               'Settings',
  'settings.language':            'Language',
  'settings.downloading_language':'Downloading language...',
  'settings.language_unavailable':'Language unavailable offline. Connect to download.',
  'settings.profile':             'Profile',
  'settings.notifications':       'Notifications',
  'settings.privacy':             'Privacy',
  'settings.about':               'About',
  'settings.version':             'Version',
  'settings.logout':              'Logout',
  'settings.delete_account':      'Delete Account',

  // ── Profile ───────────────────────────────────────────────────────────────
  'profile.title':                'Profile',
  'profile.first_name':           'First Name',
  'profile.last_name':            'Last Name',
  'profile.phone':                'Phone Number',
  'profile.dob':                  'Date of Birth',
  'profile.gender':               'Gender',
  'profile.weight':               'Weight (kg)',
  'profile.height':               'Height (cm)',
  'profile.edit_photo':           'Edit Photo',
  'profile.save_changes':         'Save Changes',

  // ── Errors ────────────────────────────────────────────────────────────────
  'error.generic':                'Something went wrong. Please try again.',
  'error.network':                'No internet connection.',
  'error.session_expired':        'Session expired. Please log in again.',
  'error.invalid_credentials':    'Invalid email or password.',
  'error.required_field':         'This field is required.',
  'error.invalid_email':          'Please enter a valid email.',
  'error.password_too_short':     'Password must be at least 8 characters.',
  'error.passwords_no_match':     'Passwords do not match.',
  'error.server':                 'Server error. Please try again later.',

  // ── Common labels ─────────────────────────────────────────────────────────
  'label.loading':                'Loading...',
  'label.no_results':             'No results found.',
  'label.today':                  'Today',
  'label.yesterday':              'Yesterday',
  'label.this_week':              'This Week',
  'label.optional':               'Optional',
  'label.required':               'Required',
  'label.or':                     'or',
  'label.search':                 'Search',
  'label.filter':                 'Filter',
  'label.sort':                   'Sort',
  'label.all':                    'All',
  'label.active':                 'Active',
  'label.inactive':               'Inactive',

  // ── Onboarding ────────────────────────────────────────────────────────────
  'onboarding.get_started':       'Get Started',
  'onboarding.welcome':           'Welcome to Amirani',
  'onboarding.subtitle':          'Your Personal Fitness Platform',
};
